//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Mrv.Regatta.PreisDesMinisterpraesidenten.Db.DataModels
{
	/// <summary>
	/// Database       : Zeitmess
	/// Data Source    : C:\regatta_lm\zeitmess\Zeitmess.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class ZeitmessDB : LinqToDB.Data.DataConnection
	{
		public ITable<ALauftyp>   ALauftyps   { get { return this.GetTable<ALauftyp>(); } }
		public ITable<Bem>        Bems        { get { return this.GetTable<Bem>(); } }
		public ITable<Schiri>     Schiris     { get { return this.GetTable<Schiri>(); } }
		public ITable<TLauftyp>   TLauftyps   { get { return this.GetTable<TLauftyp>(); } }
		public ITable<ZielZeiten> ZielZeitens { get { return this.GetTable<ZielZeiten>(); } }

		public ZeitmessDB()
		{
			InitDataContext();
		}

		public ZeitmessDB(string configuration)
			: base(configuration)   
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("ALauftyp", IsView=true)]
	public partial class ALauftyp
	{
		[Identity          ] public int    Index   { get; set; } // Long
		[Column,   Nullable] public string LaufTyp { get; set; } // text(50)
	}

	[Table("Bems")]
	public partial class Bem
	{
		[Column(),      PrimaryKey, Nullable] public int?   ID         { get; set; } // Long
		[Column("Bem"),             Nullable] public string Bem_Column { get; set; } // text(5)
		[Column(),                  Nullable] public string BemL       { get; set; } // text(50)
	}

	[Table("Schiris")]
	public partial class Schiri
	{
		[PrimaryKey, Identity] public int    ID        { get; set; } // Long
		[Column,     Nullable] public string SchirName { get; set; } // text(50)
	}

	[Table("TLauftyp")]
	public partial class TLauftyp
	{
		[PrimaryKey, Identity] public int    Index    { get; set; } // Long
		[Column,     Nullable] public string LaufTyp  { get; set; } // text(50)
		[Column,     Nullable] public string LaufTypL { get; set; } // text(50)
	}

	[Table("ZielZeiten")]
	public partial class ZielZeiten
	{
		[PrimaryKey, Identity] public int    ID         { get; set; } // Long
		[Column,     Nullable] public string Zeit       { get; set; } // text(255)
		[Column,     Nullable] public string StartNr    { get; set; } // text(2)
		[Column,     Nullable] public string RennNr     { get; set; } // text(6)
		[Column,     Nullable] public string LaufTyp    { get; set; } // text(4)
		[Column,     Nullable] public char?  AbtNr      { get; set; } // text(1)
		[Column,     Nullable] public char?  Start      { get; set; } // text(1)
		[Column,     Nullable] public int?   Schiri     { get; set; } // Long
		[Column,     Nullable] public int?   Bem        { get; set; } // Long
		[Column,     Nullable] public string Bemerkung  { get; set; } // text(255)
		[            Identity] public bool   Zeitgleich { get; set; } // Bit
	}

	public static partial class TableExtensions
	{
		public static Bem Find(this ITable<Bem> table, int? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Schiri Find(this ITable<Schiri> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static TLauftyp Find(this ITable<TLauftyp> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static ZielZeiten Find(this ITable<ZielZeiten> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
